# runtime: nodejs20

# handlers:
#   # Sert tous les fichiers statiques (JS, CSS, images, etc.)
#   - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|txt|woff2?))$
#     static_files: build/\1
#     upload: build/.*

#   # Toutes les autres URL renvoient vers index.html (React Router SPA)
#   - url: /.*
#     static_files: build/index.html
#     upload: build/index.html
runtime: nodejs20
env: standard
entrypoint: node server.js
