name: Deploy Backend to AWS Elastic Beanstalk (Simple)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create deployment directory
      run: |
        mkdir deploy
        cp -r backend/* deploy/
        cp -r .ebextensions deploy/ || true
        
    - name: Install production dependencies
      run: |
        cd deploy
        npm install --production
        
    - name: Create deployment ZIP
      run: |
        cd deploy
        zip -r ../deployment.zip . -x "*.git*" "node_modules/.cache/*"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APPLICATION_NAME }} \
          --version-label "v${{ github.run_number }}-${{ github.sha }}" \
          --source-bundle S3Bucket="${{ secrets.EB_S3_BUCKET }}",S3Key="deployments/v${{ github.run_number }}-${{ github.sha }}.zip"
          
        aws s3 cp deployment.zip s3://${{ secrets.EB_S3_BUCKET }}/deployments/v${{ github.run_number }}-${{ github.sha }}.zip
        
        aws elasticbeanstalk update-environment \
          --application-name ${{ secrets.EB_APPLICATION_NAME }} \
          --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
          --version-label "v${{ github.run_number }}-${{ github.sha }}"